{{- if and .Values.monitoring .Values.monitoring.createPrometheusRules }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: rook-prometheus
    role: alert-rules
{{- if  .Values.monitoring.prometheusRule.labels }}
{{ toYaml .Values.monitoring.prometheusRule.labels | indent 4 }}
{{- end }}
{{- if .Values.monitoring.prometheusRule.annotations }}
  annotations:
{{ toYaml .Values.monitoring.prometheusRule.annotations | indent 4 }}
{{- end }}
  name: prometheus-ceph-rules
  namespace: {{ default .Release.Namespace .Values.monitoring.rulesNamespaceOverride }}
spec:
{{- $defaultRules := "" -}}
{{- if and .Values.cephClusterSpec.external .Values.cephClusterSpec.external.enable }}
{{- $defaultRules = .Files.Get "prometheus/externalrules.yaml" | fromYaml -}}
{{- else }}
{{- $defaultRules = .Files.Get "prometheus/localrules.yaml" | fromYaml -}}
{{- end }}
{{- $mergedRules := mustMerge .Values.monitoring.editPrometheusRules $defaultRules -}}
{{- range $groupName, $groupRules := $mergedRules }}
{{- $rules := list -}}
{{- range $_, $rule := $groupRules }}
{{- if not $rule.disabled }}
{{- $rules = append $rules (unset $rule "disabled") -}}
{{- end }}
{{- end }}
{{- if gt (len $rules) 0 }}
  - name: {{ $groupName }}
    rules:
{{- toYaml $rules | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
